In [1]:
import numpy as np

In [2]:
# Activation functions
def ReLU(x):
    return np.maximum(0,x)

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))  # stability trick
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

def hidden_layer(X, W, b):
    return ReLU(np.dot(X, W) + b)

def output_layer(X, W, b):
    return softmax(np.dot(X, W) + b)

def forward_pass(X, w, b):
    a = X
    for i in range(len(w) - 1):
        a = hidden_layer(a, w[i], b[i])
    out = output_layer(a, w[-1], b[-1])
    return a, out

In [3]:
# From here Trying out multi layear network myself is it correct? will it work?

# Example architecture: 10 -> 8 -> 6 -> 4 -> 2
layer_dims = [10, 8, 6, 4, 2]

# Layers parameters
w = [np.random.randn(layer_dims[i], layer_dims[i+1]) * 0.1 for i in range(len(layer_dims)-1)]
b = [np.zeros((1, layer_dims[i+1])) for i in range(len(layer_dims)-1)]

print("W: \n", w[0:-1])
print("b: \n", b[0:-1])
print("w_out: \n", w[-1])
print("b_out: \n", b[-1])

W: 
 [array([[ 0.24258766,  0.04647581,  0.09941966, -0.12317435, -0.00274611,
        -0.08043593, -0.02447189,  0.02304698],
       [ 0.03343768,  0.02474485,  0.05070273, -0.15069997,  0.32197893,
        -0.08783124,  0.16797219, -0.0207166 ],
       [ 0.00542027, -0.03328629,  0.07393031,  0.07380803, -0.03342729,
        -0.01484091, -0.09868081, -0.02249296],
       [ 0.04361631,  0.19871496,  0.03889683,  0.06392633, -0.03441377,
         0.06533847, -0.04337584, -0.03273963],
       [-0.2078065 , -0.14729103, -0.04237087,  0.10639233,  0.0068461 ,
        -0.00620851,  0.07610503,  0.13363049],
       [ 0.15670386, -0.18952648, -0.19381141,  0.0310849 , -0.00383376,
         0.09824149,  0.09322388, -0.02071304],
       [ 0.0227854 , -0.03854129,  0.12432124,  0.00233107,  0.03037563,
         0.18549969,  0.16423461,  0.02990628],
       [ 0.05411467,  0.00254561, -0.05180247,  0.01099708,  0.00983879,
         0.02844275,  0.07054766,  0.0901384 ],
       [ 0.00432339,  0.04

In [4]:
# Input data
X = np.random.randn(10, 10)
print("X: \n", X)

X: 
 [[ 1.18457511 -0.06326808  0.26599872  0.45823084  0.44444526 -0.7947696
  -0.00651955  1.4392933   0.85592233  0.18797013]
 [-0.04799543 -1.97624173 -0.45553523 -0.98029504  1.07434074 -0.18725615
   0.64882941  0.61697884 -0.93023708  0.39720951]
 [ 0.37092508 -0.11579832 -2.08832568  1.17612609  0.57663411 -0.92739276
   0.90754568  0.73590474  0.87659618 -0.622535  ]
 [-0.20518782 -1.16814309 -0.98873806  1.41185215  0.36606244  1.85688309
  -1.35099275 -2.29012603  0.32533878 -0.81829522]
 [ 0.58493986 -0.18296543 -2.18590888  0.66886993  0.05306241  0.0583792
  -0.91453022  0.57930641  0.20199915 -1.27520642]
 [ 1.03965306  1.41286495 -0.25677077  0.00585036  1.7439926  -0.80388802
  -1.40056105  0.04074838 -0.77755758 -1.07600096]
 [ 0.23006787 -0.3084173   0.67723349 -0.45511456  0.2856504   1.44612649
  -0.99646794  0.0878131   1.23842804 -0.11030755]
 [-0.5158799  -0.10642983 -0.24742539 -0.44031772  1.06512804  1.68064792
  -0.85577035  0.55096128 -0.96934192 -0.0652078

In [5]:
# Forward pass
x_out, output = forward_pass(X, w, b)

print("x_out: \n", x_out)
print("output: \n", output)

x_out: 
 [[0.         0.00081665 0.         0.00346269]
 [0.         0.         0.         0.00738393]
 [0.         0.         0.         0.00296891]
 [0.         0.         0.         0.0108806 ]
 [0.         0.00067784 0.         0.00070976]
 [0.00382909 0.00038721 0.         0.00215109]
 [0.         0.00119274 0.         0.00132538]
 [0.         0.         0.         0.00821876]
 [0.         0.         0.         0.00976589]
 [0.         0.         0.         0.00586871]]
output: 
 [[0.50007241 0.49992759]
 [0.50013581 0.49986419]
 [0.50005461 0.49994539]
 [0.50020012 0.49979988]
 [0.5000203  0.4999797 ]
 [0.49996223 0.50003777]
 [0.50003712 0.49996288]
 [0.50015116 0.49984884]
 [0.50017962 0.49982038]
 [0.50010794 0.49989206]]
