In [2]:
import numpy as np

In [3]:
# Activation functions
def ReLU(x):
    return np.maximum(0,x)

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))  # stability trick
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

def hidden_layer(X, W, b):
    return ReLU(np.dot(X, W) + b)

def output_layer(X, W, b):
    return softmax(np.dot(X, W) + b)

def forward_pass(X, w, b):
    a = X
    for i in range(len(w) - 1):
        a = hidden_layer(a, w[i], b[i])
    out = output_layer(a, w[-1], b[-1])
    return a, out

In [ ]:
# From here Trying out multi layear network myself is it correct? will it work?

# Example architecture: 10 -> 8 -> 6 -> 4 -> 2
layer_dims = [10, 8, 6, 4, 2]

# Layers parameters
w = [np.random.randn(layer_dims[i], layer_dims[i+1]) * 0.1 for i in range(len(layer_dims)-1)]
b = [np.zeros((1, layer_dims[i+1])) for i in range(len(layer_dims)-1)]


print("W: \n", w[0:-1])
print("b: \n", b[0:-1])
print("w_out: \n", w[-1])
print("b_out: \n", b[-1])

W: 
 [array([[ 0.12992591,  0.02912037,  0.09061172,  0.06001396, -0.05689722,
        -0.04202574, -0.1749549 , -0.1382585 ],
       [-0.01516792,  0.00091221, -0.13474312,  0.10112164,  0.10067058,
        -0.11805472,  0.05040065,  0.15602846],
       [ 0.15486136, -0.05377893,  0.06206869,  0.15914348, -0.091814  ,
         0.04983081,  0.03874378, -0.02038251],
       [ 0.02279826,  0.07533766, -0.08920361,  0.06187347, -0.05897655,
        -0.12538747, -0.00754938, -0.04921316],
       [-0.1327243 ,  0.17054975,  0.00393906, -0.16262892, -0.05383113,
         0.08795781,  0.07081537,  0.02591876],
       [ 0.02946007, -0.04109351, -0.01973797, -0.0862158 ,  0.08701181,
        -0.11947933, -0.19716201,  0.09296064],
       [ 0.10694022, -0.05571673,  0.05907527, -0.11647515, -0.15065566,
        -0.04053117,  0.00681657, -0.05535894],
       [ 0.11349375, -0.05525457, -0.10820377, -0.04442835, -0.00360964,
        -0.0073232 , -0.01115541,  0.10088853],
       [-0.10922995, -0.04

In [5]:
# Input data
X = np.random.randn(10, 10)
print("X: \n", X)

X: 
 [[-1.04098730e+00  7.15108510e-01 -9.19888732e-01  5.09278030e-01
   6.62211486e-02  2.87313187e-01  3.19853615e-01 -3.90034011e-01
   1.93612122e+00  7.28532530e-01]
 [ 2.18136430e+00  9.94713338e-01 -8.58795448e-01 -5.48546739e-01
  -7.38433781e-01 -7.49437559e-01  9.06057456e-01  9.12065546e-01
  -9.65761584e-01 -2.10962484e-01]
 [-9.25992100e-01  1.09043181e+00  4.09216507e-01 -7.62491730e-01
   1.01778154e+00 -8.11421610e-01  1.86972795e+00  2.38068663e-01
  -2.65104808e-03  4.55739758e-01]
 [-7.89455540e-01  3.88222447e-01 -6.92521188e-01  1.17379830e+00
   1.38641900e-01 -5.08960041e-01 -5.52807931e-01 -5.19308303e-01
  -4.16826010e-02 -4.67506500e-02]
 [ 4.07108963e-01  4.06727517e-01 -1.30780705e+00  1.11478628e+00
   7.59631356e-01  3.09554421e-01 -5.61927689e-01 -2.76224217e+00
   1.64350902e+00 -1.15193155e+00]
 [-2.13800371e-01  2.62632555e-01 -1.82953243e-01  2.68190467e-01
  -4.78314312e-01  5.89123883e-03  2.90091596e-01 -1.56989382e+00
  -5.92083572e-02  3.5648110

In [6]:
# Forward pass
x_out, output = forward_pass(X, w, b)

print("x_out: \n", x_out)
print("output: \n", output)

x_out: 
 [[0.         0.         0.         0.00274978]
 [0.         0.         0.00459253 0.00175974]
 [0.         0.         0.         0.00243761]
 [0.         0.         0.00057628 0.00357265]
 [0.         0.00109624 0.0001492  0.00229945]
 [0.         0.00034196 0.00381582 0.00250217]
 [0.         0.         0.01245962 0.01098287]
 [0.         0.         0.         0.        ]
 [0.         0.         0.01029348 0.00349106]
 [0.         0.00209694 0.00020434 0.00129335]]
output: 
 [[0.49998828 0.50001172]
 [0.49998752 0.50001248]
 [0.49998961 0.50001039]
 [0.49998415 0.50001585]
 [0.49993485 0.50006515]
 [0.49996798 0.50003202]
 [0.49993969 0.50006031]
 [0.5        0.5       ]
 [0.49997396 0.50002604]
 [0.4998887  0.5001113 ]]
