In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))
print(np.power(arr,3))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1  8 27 64]


In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [4]:
arr = np.random.randint(1, 100, 10)
print(arr)

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Sum:", np.sum(arr))                      

[63 74 15 25 85 23 28 59 55 12]
Mean: 43.9
Median: 41.5
Standard Deviation: 24.921677311128157
Variance: 621.0899999999999
Min: 12
Max: 85
Sum: 439


In [5]:
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

print(np.mean(matrix, axis=0))  # Column-wise
print(np.mean(matrix, axis=1))  # Row-wise

[40. 50. 60.]
[20. 50. 80.]


In [7]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(a + b)  # b is broadcast across rows
print(a * b)  # Element-wise multiplication with broadcasting

[[11 22 33]
 [14 25 36]]
[[ 10  40  90]
 [ 40 100 180]]


In [8]:
arr = np.array([5, 10, 15, 20, 25])
mask = arr > 10
print(arr[mask])
# or simply
print(arr[arr > 10])


[15 20 25]
[15 20 25]


In [13]:
arr = np.random.randint(1, 100, 50)
print("Array:\n",arr)

ans1 = arr[arr > 50]
print("\nfiltered Array (arr>50):\n", ans1)\

arr[arr < 30] = 0
print("\nArray with number less then 30 to zero:\n",arr)

Array:
 [25 47 35 24 49 84 16 69 92 22 91 46 72 48 55  6 42 56 66 10 13 49 72 19
 20 82 28 77 51 66 31  4 43 46 96 61 42 60 91 60 38  4 72 10  2 29 58 80
 59 18]

filtered Array (arr>50):
 [84 69 92 91 72 55 56 66 72 82 77 51 66 96 61 60 91 60 72 58 80 59]

Array with number less then 30 to zero:
 [ 0 47 35  0 49 84  0 69 92  0 91 46 72 48 55  0 42 56 66  0  0 49 72  0
  0 82  0 77 51 66 31  0 43 46 96 61 42 60 91 60 38  0 72  0  0  0 58 80
 59  0]


In [14]:
students = np.array([
    np.random.randint(40, 100, 4) for _ in range(5)
])

print(students)
print("Mean per student:", np.mean(students, axis=1))
print("Mean per subject:", np.mean(students, axis=0))
print("Top student index:", np.argmax(np.mean(students, axis=1)))


[[67 66 46 49]
 [43 84 81 52]
 [91 51 56 52]
 [41 74 42 74]
 [70 41 84 78]]
Mean per student: [57.   65.   62.5  57.75 68.25]
Mean per subject: [62.4 63.2 61.8 61. ]
Top student index: 4
