In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))  # 1*4 + 2*5 + 3*6 = 32

32


In [4]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(np.dot(A, B))   # same as A @ B
print(A @ B)          # preferred in modern code


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [5]:
A = np.array([[2, 3],
              [1, 4]])

det = np.linalg.det(A)
print("Determinant:", det)


Determinant: 5.000000000000001


In [10]:
inv_A = np.linalg.inv(A)
print("Inverse:\n", inv_A)
print("\nProf:\n", inv_A @ A)

Inverse:
 [[ 0.8 -0.6]
 [-0.2  0.4]]

Prof:
 [[1. 0.]
 [0. 1.]]


In [22]:
A = np.array([[2, 3],
             [81, 4]])

B = np.array([7,7])

X = np.linalg.solve(A,B)
print("Solution (x, y):", X)

Solution (x, y): [-0.02978723  2.35319149]


In [23]:
print(np.allclose(np.dot(A, X), B))

True


In [24]:
A = np.array([[4, -2],
              [1, 1]])

values, vectors = np.linalg.eig(A)
print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)


Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
