In [93]:
import numpy as np

In [94]:
# Random Seed For Reproducibility
np.random.seed(50)

# Input data (4 samples, 3 features)
X = np.random.randn(4, 3)

# Layer 1 parameters
W1 = np.random.randn(3, 5) * 0.1 # (input_features, hidden_neurons)
b1 = np.zeros((1,5))             # (1, hidden_neurons)

# Layer 2 parameters
W2 = np.random.randn(5, 2) * 0.1 # (hidden_neurons, output_neurons)
b2 = np.zeros((1, 2))            # (1, output_neurons)    

print("X: \n", X)
print("W1: \n", W1)
print("W2: \n", W2)
print("b1: \n", b1)
print("b2: \n", b2)

X: 
 [[-1.56035211 -0.0309776  -0.62092842]
 [-1.46458049  1.41194612 -0.47673214]
 [-0.78046921  1.07026774 -1.2822926 ]
 [-1.3274789   0.12633764  0.86219372]]
W1: 
 [[ 0.0696737  -0.03345652 -0.09975261  0.15989083  0.33140753]
 [ 0.09877705  0.01238663  0.07427854 -0.03939559  0.01481158]
 [-0.04122345 -0.01607151  0.01395315  0.02854694 -0.0281262 ]]
W2: 
 [[ 0.17109073 -0.01497666]
 [ 0.06903067  0.10952095]
 [ 0.13384087 -0.13689817]
 [ 0.04864276  0.07535217]
 [ 0.03634646 -0.03147105]]
b1: 
 [[0. 0. 0. 0. 0.]]
b2: 
 [[0. 0.]]


In [95]:
def ReLU(x):
    return np.maximum(0,x)

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))  # stability trick
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

In [96]:
# Forward Pass

# Layer 1 (Linear)
Z1 = np.dot(X, W1) + b1
print("Z1 shape: \n", Z1.shape)
print("Z1: \n",Z1)

print("\n\n\n")

# ReLU Activation
A1 = ReLU(Z1)
print("A1 shape: \n", A1.shape)
print("A1: \n", A1)

print("\n\n\n")

# Layer 2 (Linear)
Z2 = np.dot(A1, W2) + b2
print("Z2 shape: \n", Z2.shape)
print("Z2: \n",Z2)

print("\n\n\n")
print("Network Output:\n", Z2)

print("\n\n\n")
output = softmax(Z2)
print("Probabilities:\n", output)
print("Predicted classes:", np.argmax(output, axis=1))


Z1 shape: 
 (4, 5)
Z1: 
 [[-0.08617857  0.0617995   0.14468431 -0.26599122 -0.50010692]
 [ 0.05707767  0.07415082  0.2443211  -0.30340667 -0.45105119]
 [ 0.10420023  0.05997716  0.13945974 -0.20355922 -0.206735  ]
 [-0.1155537   0.03212097  0.15383397 -0.19261586 -0.46231548]]




A1 shape: 
 (4, 5)
A1: 
 [[0.         0.0617995  0.14468431 0.         0.        ]
 [0.05707767 0.07415082 0.2443211  0.         0.        ]
 [0.10420023 0.05997716 0.13945974 0.         0.        ]
 [0.         0.03212097 0.15383397 0.         0.        ]]




Z2 shape: 
 (4, 2)
Z2: 
 [[ 0.02363074 -0.01303868]
 [ 0.04758429 -0.02618088]
 [ 0.04063337 -0.0140836 ]
 [ 0.0228066  -0.01754167]]




Network Output:
 [[ 0.02363074 -0.01303868]
 [ 0.04758429 -0.02618088]
 [ 0.04063337 -0.0140836 ]
 [ 0.0228066  -0.01754167]]




Probabilities:
 [[0.50916633 0.49083367]
 [0.51843293 0.48156707]
 [0.51367583 0.48632417]
 [0.5100857  0.4899143 ]]
Predicted classes: [0 0 0 0]
